# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratchQs', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='community',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
